version: '3.8'
services:
  postgres:
    image: postgres:16

    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit
    ports:
      - "5432:5432"
